### ISSUE TITLE
Remove owl bcrypt dependency

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [starinjs/OwlGamingPlus#11]
Get rid of "bcrypt.dll"
It is used for password hashing and should easily be replaced with the following MTA functions:

- https://wiki.multitheftauto.com/wiki/PasswordHash
- https://wiki.multitheftauto.com/wiki/PasswordVerify

Resource affected: account
https://github.com/starinjs/OwlGamingPlus/blob/622feb63940be7d61ec1a19baf438e0a004040be/%5Bgamemode%5D/account/login-panel/server.lua#L90

**Comment by Fernando-A-Rocha** [comment]
https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L404

**Comment by YelehaUwU** [comment]
Removed BCrypt and added the passwordHash and passwordVerify functions 👍
