### ISSUE TITLE
Create data to seed/populate the database 

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [starinjs/OwlGamingPlus#12]
The data.sql file is missing important data for the server to work, like the main factions with the appropriate IDs.

https://github.com/starinjs/OwlGamingPlus/blob/main/data/mysql/data.sql

**Comment by Ianec21** [comment]
Hey, I don't really know if this is a "Issue". If you're talking about the fact that some scripts depend on faction's id, this might easily be fixed from script, by changing the faction id to faction type.

**Comment by TenpennyUMFPOS** [comment]
I think it is an issue honestly since, a lot of stuff on the server dpeneds  on at least having  one or two lines of some tables populated .. it will make it easier for newer people t scripting to get through some challenges, I think it's a good idea .. It will help me I admit.

**Comment by Fernando-A-Rocha** [comment]
There should be data for testing. At least some demo / dummy stuff.

**Comment by YelehaUwU** [comment]
Completed.
